### ISSUE TITLE
请教一下

### ISSUE THREAD

**Issue by hgh188** [maxlicheng/luci-app-ssr-plus#1]
Collected errors:
 * check_data_file_clashes: Package dnsmasq-full wants to install file /home/a/openwrt/build_dir/target-mipsel_24kc_musl/root-ramips/etc/hotplug.d/ntp/25-dnsmasqsec
	But that file is already provided by package  * dnsmasq
 * check_data_file_clashes: Package dnsmasq-full wants to install file /home/a/openwrt/build_dir/target-mipsel_24kc_musl/root-ramips/etc/init.d/dnsmasq
	But that file is already provided by package  * dnsmasq
 * check_data_file_clashes: Package dnsmasq-full wants to install file /home/a/openwrt/build_dir/target-mipsel_24kc_musl/root-ramips/usr/lib/dnsmasq/dhcp-script.sh
	But that file is already provided by package  * dnsmasq
 * check_data_file_clashes: Package dnsmasq-full wants to install file /home/a/openwrt/build_dir/target-mipsel_24kc_musl/root-ramips/usr/sbin/dnsmasq
	But that file is already provided by package  * dnsmasq
 * check_data_file_clashes: Package dnsmasq-full wants to install file /home/a/openwrt/build_dir/target-mipsel_24kc_musl/root-ramips/usr/share/acl.d/dnsmasq_acl.json
	But that file is already provided by package  * dnsmasq
 * check_data_file_clashes: Package dnsmasq-full wants to install file /home/a/openwrt/build_dir/target-mipsel_24kc_musl/root-ramips/usr/share/dnsmasq/dhcpbogushostname.conf
	But that file is already provided by package  * dnsmasq
 * check_data_file_clashes: Package dnsmasq-full wants to install file /home/a/openwrt/build_dir/target-mipsel_24kc_musl/root-ramips/usr/share/dnsmasq/rfc6761.conf
	But that file is already provided by package  * dnsmasq
 * opkg_install_cmd: Cannot install package dnsmasq-full.
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for luci-app-ssr-plus:
 * 	shadowsocksr-libev-alt
 * 	pdnsd-alt
 * opkg_install_cmd: Cannot install package luci-app-ssr-plus.
make[2]: *** [package/Makefile:68: package/install] Error 255
make[2]: Leaving directory '/home/a/openwrt'
make[1]: *** [package/Makefile:104: /home/a/openwrt/staging_dir/target-mipsel_24kc_musl/stamp/.package_install] Error 2
make[1]: Leaving directory '/home/a/openwrt'
make: *** [/home/a/openwrt/include/toplevel.mk:218：world] 错误 2

**Comment by hgh188** [comment]
WARNING: Makefile 'package/openwrt-packages/luci-app-ssr-plus/Makefile' has a dependency on 'shadowsocksr-libev-alt', which does not exist
WARNING: Makefile 'package/openwrt-packages/luci-app-ssr-plus/Makefile' has a dependency on 'pdnsd-alt', which does not exist
WARNING: Makefile 'package/openwrt-packages/luci-app-ssr-plus/Makefile' has a dependency on 'v2ray', which does not exist
WARNING: Makefile 'package/openwrt-packages/luci-app-ssr-plus/Makefile' has a dependency on 'kcptun-client', which does not exist
WARNING: Makefile 'package/openwrt-packages/luci-app-ssr-plus/Makefile' has a dependency on 'shadowsocksr-libev-server', which does not exist
WARNING: Makefile 'package/openwrt-packages/luci-app-ssr-plus/Makefile' has a dependency on 'shadowsocksr-libev-ssr-local', which does not exist

**Comment by maxlicheng** [comment]
是L大的源码嘛？git pull 了嘛？ 试试第二种方法。

**Comment by hgh188** [comment]
lede正常装上依赖   openwrt不行  都一样git pull

**Comment by maxlicheng** [comment]
这个是L大lede源码备份的ssr，所以openwrt 源码不一定适用。


发自我的iPhone

------------------ 原始邮件 ------------------
发件人: hgh188 <notifications@github.com>
发送时间: 2019年5月21日 21:14
收件人: maxlicheng/luci-app-ssr-plus <luci-app-ssr-plus@noreply.github.com>
抄送: maxlicheng <1661695769@qq.com>, Comment <comment@noreply.github.com>
主题: 回复：[maxlicheng/luci-app-ssr-plus] 请教一下 (#1)
