### ISSUE TITLE
能否加入服务器监测功能，以及显示延迟

### ISSUE THREAD

**Issue by choushui007** [maxlicheng/luci-app-ssr-plus#3]
现在虽然知道哪个服务器能通，但是有些拥堵得太厉害，想自动回避这些拥堵节点

**Comment by maxlicheng** [comment]
> 现在虽然知道哪个服务器能通，但是有些拥堵得太厉害，想自动回避这些拥堵节点

此仓库只做个人备份用，如有需要请到插件原作者 [[Lean]](https://github.com/coolsnowwolf) 的 [[LEDE仓库]](https://github.com/coolsnowwolf/lede)进行反馈。
