### ISSUE TITLE
使用方法错误

### ISSUE THREAD

**Issue by alexyw** [maxlicheng/luci-app-ssr-plus#5]
方法二：
    #源码根目录，编辑.gitignore文件
    vi .gitignore
    #在文件最后一行，加入
    git rm --cached package/lean/luci-app-ssr-plus/ -r
    #保存后，进入lean源码目录
    cd package/lean/
    #下载源码
    git clone https://github.com/maxlicheng/luci-app-ssr-plus.git
    #回到源码根目录
    cd ../..
    #拉取源码
    git pull

应该改为：
    #源码根目录，编辑.gitignore文件
    vi .gitignore
    #在文件“/package/openwrt-packages”一行下面，加入
    /package/lean/luci-app-ssr-plus
其他都可以

**Comment by maxlicheng** [comment]
并不冲突，两个方法，源码下载的路径不一样。方法一是新建一个目录，方法二是下载到lean原本目录。所以方法并无问题。

**Comment by sxml** [comment]
小白我 请教可以在后台 web 列表 软件包 升级吗? 
怎么升级插件 还有固件?
