### ISSUE TITLE
shadowsocksr.lua 怎么乱码呀？

### ISSUE THREAD

**Issue by 414791324** [maxlicheng/luci-app-ssr-plus#7]
shadowsocksr.lua 怎么乱码呀？

**Comment by maxlicheng** [comment]
> shadowsocksr.lua 怎么乱码呀？

此仓库只做个人备份用，如有需要请到插件原作者 [[Lean]](https://github.com/coolsnowwolf) 的 [[LEDE仓库]](https://github.com/coolsnowwolf/lede)进行反馈。
